# Generated by Django 5.2.4 on 2025-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_agreed',
            field=models.BooleanField(default=False, help_text='이벤트 및 혜택 정보 수신 동의 여부(선택)', verbose_name='마케팅 정보 수신 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_agreed',
            field=models.BooleanField(default=False, help_text='개인정보 수집 및 이용 동의 여부(필수)', verbose_name='개인정보 처리방침 동의'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_agreed',
            field=models.BooleanField(default=False, help_text='서비스 이용약관 동의 여부(필수)', verbose_name='서비스 이용약관 동의'),
        ),
    ]
