# Generated by Django 5.2.3 on 2025-08-07 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyworkout',
            name='unique_member_workout_date',
        ),
        migrations.AlterField(
            model_name='dailyworkout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts_as_member', to=settings.AUTH_USER_MODEL, verbose_name='운동하는 사용자 (회원 또는 트레이너)'),
        ),
        migrations.AlterField(
            model_name='dailyworkout',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_workouts_as_trainer', to='members.trainer', verbose_name='등록한 트레이너'),
        ),
        migrations.AddConstraint(
            model_name='dailyworkout',
            constraint=models.UniqueConstraint(fields=('member', 'workout_date'), name='unique_user_workout_date'),
        ),
    ]
