# Generated by Django 5.2.4 on 2025-07-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 수정에서 업로드', null=True, upload_to='trainer_profile/', verbose_name='프로필 이미지')),
                ('age', models.PositiveIntegerField(blank=True, help_text='프로필 수정에서 입력', null=True, verbose_name='나이')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='키(cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='몸무게(kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=4, null=True, verbose_name='체지방률(%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=5, null=True, verbose_name='골격근량(kg)')),
                ('profile_complated', models.BooleanField(default=False, help_text='프로필 정보가 모두 입력되었는지 확인', verbose_name='프로필 완성 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('user', models.OneToOneField(help_text='연결된 사용자 계정', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '트레이너',
                'verbose_name_plural': '트레이너들',
                'db_table': 'trainer',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 수정에서 업로드', null=True, upload_to='member_profile/', verbose_name='프로필 이미지')),
                ('age', models.PositiveIntegerField(blank=True, help_text='프로필 수정에서 입력', null=True, verbose_name='나이')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='키(cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='몸무게(kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=4, null=True, verbose_name='체지방률(%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=5, null=True, verbose_name='골격근량(kg)')),
                ('profile_completed', models.BooleanField(default=False, help_text='프로필 정보가 모두 입력되었는지 확인', verbose_name='프로필 완성 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(help_text='연결된 사용자 계정', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('trainer', models.ForeignKey(help_text='소속 트레이너', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.trainer', verbose_name='담당 트레이너')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'member',
            },
        ),
    ]
