# Generated by Django 5.2.4 on 2025-08-02 09:57

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 수정에서 업로드', null=True, upload_to='trainer_profile/', verbose_name='프로필 이미지')),
                ('age', models.PositiveIntegerField(blank=True, help_text='프로필 수정에서 입력', null=True, verbose_name='나이')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='키(cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='몸무게(kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=4, null=True, verbose_name='체지방률(%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=5, null=True, verbose_name='골격근량(kg)')),
                ('profile_completed', models.BooleanField(default=False, help_text='프로필 정보가 모두 입력되었는지 확인', verbose_name='프로필 완성 여부')),
            ],
            options={
                'verbose_name': '트레이너',
                'verbose_name_plural': '트레이너들',
                'db_table': 'trainer',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 수정에서 업로드', null=True, upload_to='member_profile/', verbose_name='프로필 이미지')),
                ('age', models.PositiveIntegerField(blank=True, help_text='프로필 수정에서 입력', null=True, verbose_name='나이')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='키(cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='프로필 수정에서 입력', max_digits=5, null=True, verbose_name='몸무게(kg)')),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=4, null=True, verbose_name='체지방률(%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='키/몸무게 기반 자동 계산', max_digits=5, null=True, verbose_name='골격근량(kg)')),
                ('profile_completed', models.BooleanField(default=False, help_text='프로필 정보가 모두 입력되었는지 확인', verbose_name='프로필 완성 여부')),
                ('assigned_trainer', models.ForeignKey(blank=True, db_column='trainer_id', help_text='소속 트레이너', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.trainer', verbose_name='담당 트레이너')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'member',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
