# Generated by Django 5.2.4 on 2025-08-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='소속 트레이너', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.trainer', verbose_name='담당 트레이너'),
        ),
    ]
